# Generated by Django 6.0 on 2026-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0012_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='extra_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
