# Generated by Django 6.0 on 2026-01-27 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0017_orderitem_delete_coupon_remove_cart_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationitem',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='customizationitem',
            name='option',
        ),
        migrations.RemoveField(
            model_name='customizedoption',
            name='food',
        ),
        migrations.RenameField(
            model_name='baseoption',
            old_name='basetype',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sauceoption',
            old_name='sausetype',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sizeoption',
            old_name='size',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='toppingoption',
            old_name='toppingname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='baseoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='baseoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='catogery',
        ),
        migrations.RemoveField(
            model_name='sauceoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sauceoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sizeoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sizeoption',
            name='image',
        ),
        migrations.RemoveField(
            model_name='toppingoption',
            name='category',
        ),
        migrations.RemoveField(
            model_name='toppingoption',
            name='image',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRIES', 'French Fries'), ('DESSERTS', 'Desserts'), ('BEVERAGES', 'Beverages'), ('BRIYANI', 'Briyani')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseoption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsapp.fooditems'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sauceoption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsapp.fooditems'),
        ),
        migrations.AlterField(
            model_name='sizeoption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsapp.fooditems'),
        ),
        migrations.AlterField(
            model_name='toppingoption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsapp.fooditems'),
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='CustomizationItem',
        ),
        migrations.DeleteModel(
            name='CustomizedOption',
        ),
    ]
