# Generated by Django 6.0 on 2026-01-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0018_remove_customizationitem_customization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseoption',
            old_name='name',
            new_name='basetype',
        ),
        migrations.RenameField(
            model_name='sauceoption',
            old_name='name',
            new_name='sausetype',
        ),
        migrations.RenameField(
            model_name='sizeoption',
            old_name='name',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='toppingoption',
            old_name='name',
            new_name='toppingname',
        ),
        migrations.AddField(
            model_name='baseoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/'),
        ),
        migrations.AddField(
            model_name='sauceoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sauce/'),
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='size/'),
        ),
        migrations.AddField(
            model_name='toppingoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topping/'),
        ),
    ]
